---
repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
        name: gitleaks (detect)
        entry: gitleaks detect
        args:
          - --source
          - .
          - --redact
          - --report-format
          - json
          - --report-path
          - gitleaks-report.json
          - --exit-code
          - "1"
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.23.1
    hooks:
      - id: toml-sort
