services:
  ui:
    # You can add local-only tweaks here; keep it minimal to avoid drift.
    # Ports are already set in base, but keeping it here is fine for clarity.
    ports:
      - ":3000"# test
