services:
  ollama:
    image: ollama/ollama:0.3.12
    container_name: chill_ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:11434/api/tags"]
      interval: 10s
      timeout: 3s
      retries: 30
      start_period: 10s

volumes:
  ollama_data:
