services:
  api:
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      BIND_HOST: "0.0.0.0"
      PORT: "8000"
      CHAT_ECHO: "false"
      SEC_PATCH_11: "off"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    ports:
      - "8000:8000"
  ui:
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "3000:3000"
