services:
  api:
    environment:
      - CHAT_ECHO=
      - GEMINI_API_KEY
      - GROQ_API_KEY
      - MISTRAL_API_KEY
    volumes:
      - ./operator.manifest.json:/app/operator.manifest.json:ro


