/** Auto-generated by Operator */
const nextConfig = {
  async rewrites() {
    return [
      { source: "/bridge/chat", destination: "http://api:8000/chat" },
      // keep a generic pass-through too:
      { source: "/api/:path*", destination: "http://api:8000/:path*" },
    ];
  },
  reactStrictMode: true,
};
module.exports = nextConfig;
