guards:
  lint_type_gate: true
  block_open_rca: true
  health_swap: true
  preflight: true
schema: operator.v3
mode: developer
paste_ready_code: true
one_step: true
docker:
  api_service: chill_api
  ui_service: chill_ui
risk_meter: "on"
network:
  bridge_endpoint: /bridge/chat
  api_port: 8000
  ui_port: 3000
paths:
  scripts: C:\AiProject\scripts
  api: C:\AiProject\chatbot\agent-api
  logs: C:\AiProject\logs
  root: C:\AiProject
  ui: C:\AiProject\chatbot\chatbot-ui

