---
name: CI
on:
  pull_request:
    branches: ["main"]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sanity
        run: echo "CI sanity ok"
