---
name: Security
"on":
  pull_request:
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install pyyaml
      - name: Enforce security policy
        run: python .github/scripts/policy_gate.py security_policy.yaml
      - name: Gitleaks scan
        uses: zricethezav/gitleaks-action@v2
        with:
          config-path: gitleaks.toml
          args: "--no-banner"
