name: UI Dark Theme Smoke
on:
  pull_request:
  push:
    branches: [ main, master ]
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build & run UI (compose)
        run: |
          docker compose build ui
          docker compose up -d ui api
          # give Next.js a moment to warm
          sleep 10
      - name: Assert dark class on /
        run: |
          set -e
          code=$(curl -s -o /tmp/index.html -w "%{http_code}" http://localhost:3000/ || true)
          echo "HTTP: $code"
          test "$code" = "200"
          grep -E '<html[^>]*class="[^"]*dark' /tmp/index.html